repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_docs
    - id: terraform_tfsec
    - id: terraform_validate
    - id: checkov

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
